### ISSUE TITLE
Rename occ command s3:ls to s3:list for better identification

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_primary_s3#111]
The current command ``s3:ls`` ``List objects, buckets or versions of an object`` has imho a bad naming.
To improve that I propose to rename it to ``s3:list``.

This would also be inline with other occ commands wher we use eg. 
``--list`` as option like ``user:sync --list``.

@DeepDiver1975 @patrickjahns

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @DeepDiver1975.

Possibly related issues are https://github.com/owncloud/files_primary_s3/pull/8 (Add s3:ls to list buckets, objects and versions), and https://github.com/owncloud/files_primary_s3/pull/93 (- adding s3:createBucket command).

**Comment by mmattel** [comment]
Closing, PR merged
