### ISSUE TITLE
make test-php-style

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_primary_s3#116]
For harmonisation, it would be good to have a ``make test-php-style`` as we have eg in core.
Please see also documentation: https://github.com/owncloud/documentation/issues/4064#issuecomment-412053981 plus follow up comment

This would: 
- ease up development
- have a documentation that matches different repo setups

@phil-davis @DeepDiver1975 

Part of https://github.com/owncloud/QA/issues/582

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/files_primary_s3/issues/55 (php-cs-fixer), https://github.com/owncloud/files_primary_s3/pull/28 (Test against master again), https://github.com/owncloud/files_primary_s3/pull/13 (Test with php 5.6 up to 7.2 - ensure composer compatibility with php 5.6), https://github.com/owncloud/files_primary_s3/issues/49 (Add unit tests), and https://github.com/owncloud/files_primary_s3/issues/86 (Add litmus to testing pipeline).

**Comment by phil-davis** [comment]
I an currently looking to create a standard set of CI-drone-Makefile-test scripts in each app repo. So this will happen naturally as I do that.
