### ISSUE TITLE
Support user based multi bucket support

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_primary_s3#131]
Some Customer has the follwing problem.

> Currently we using the objectstore enterprise app for our ResearchDrive environment.
> We like to upgrade to the new files_primary_s3 app, but it’s hard where we have enable multi bucket in our setup.
>Now a days we have 250 buckets, 8 million files, 17 million objects with a total of 190TiB of data.

> Yesterday we already discussed the possibilities to migratie from the current app to the new app with Thomas Müller.
>But we came to the conclusion that's hard and risk full to migrate all objects from multi bucket to one bucket without a long downtime.

>Could it maybe possible to support multi bucket in the new files_primary_s3 app what makes a migration lot easier?

>If we can help some how, please let us know!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/files_primary_s3/pull/10 (Verisoned buckets), and https://github.com/owncloud/files_primary_s3/pull/96 (Remove "Support" from name in info.xml).

**Comment by micbar** [comment]
@pmaier1 The customer just contacted us. Are there news? Timeline?

**Comment by DeepDiver1975** [comment]
As far as I can tell after a second look this should work out of the box. Operators have to make sure all required buckets exist ..... ~40k need to be created .....

**Comment by pmaier1** [comment]
>  ~40k need to be created .....

How do you derive that number and what does it mean for the customer?

**Comment by DeepDiver1975** [comment]
3 chars in the range a-z0-9: 34x34x34

How to compute the bucket Name: bucket Name as per config.php+First 3 chars of md5(userid)

**Comment by micbar** [comment]
Customer is happy. Closing Ticket.
