### ISSUE TITLE
can this package work as a standalone s3 uploader? 

### ISSUE THREAD

**Issue by inglesuniversal** [owncloud/files_primary_s3#137]
Do you have wiki page for install instructions and basic config and requirements?

Regards

**Comment by patrickjahns** [comment]
This repository hosts an onwCloud application (`files_primary_s3`) which provides primary storage via s3 on an ownCloud instance. 
More information can be found here https://doc.owncloud.com/server/admin_manual/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.html#amazon-s3
