### ISSUE TITLE
Add occ command acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_primary_s3#139]
Make ``cli`` acceptance tests for the various files_primary_s3 ``occ`` commands.

Main QA issue: https://github.com/owncloud/QA/issues/570

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/files_primary_s3/pull/80 (Adding command to explicit create abucket), https://github.com/owncloud/files_primary_s3/pull/109 (Use core acceptance tests run.sh), https://github.com/owncloud/files_primary_s3/pull/129 (skip acceptance tests for specific storage), https://github.com/owncloud/files_primary_s3/pull/105 (Rename test-acceptance.sh script), and https://github.com/owncloud/files_primary_s3/pull/122 (su-exec www-data is not needed for acceptance tests).

**Comment by paurakhsharma** [comment]
This is blocked because of https://github.com/owncloud/files_primary_s3/issues/179 and also the requirement of bucket is not clear (e.g if I create a new bucket and upload some files and change the bucket then I was able to see the files from previous bucket. Is this the expected behaviour?)

**Comment by DeepDiver1975** [comment]
not critical -> close
