### ISSUE TITLE
occ versions:cleanup does not work with S3

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_primary_s3#155]
1. setup files_primary_s3
1. create multiple versions of a file
1. check in the UI that there are multiple versions listed
1. run `./occ  versions:cleanup`

in the webUI still multiple versions are displayed

see tests added by https://github.com/owncloud/core/pull/33585

- [ ] tests were skipped and marked in https://github.com/owncloud/core/pull/33618 and https://github.com/owncloud/core/pull/33619 **unskip them**

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/files_primary_s3/issues/67 (Thumbnail preview of last version of a file does not work with scality), https://github.com/owncloud/files_primary_s3/issues/72 (Gallery app does not work with Scality/Ceph), https://github.com/owncloud/files_primary_s3/pull/8 (Add s3:ls to list buckets, objects and versions), https://github.com/owncloud/files_primary_s3/issues/137 (can this package work as a standalone s3 uploader? ), and https://github.com/owncloud/files_primary_s3/issues/111 (Rename occ command s3:ls to s3:list for better identification).

**Comment by PVince81** [comment]
it will not work because versioning is completely different

all occ commands related to version are going to the files_version app which expects files to exist in "files_versions/*" in the storage. on S3 the versions are stored differently.

**Comment by PVince81** [comment]
cc @DeepDiver1975 we already knew that

**Comment by DeepDiver1975** [comment]
as per design of s3 versioning this is not possible -> close
