### ISSUE TITLE
[For Semver] Files Primary S3 1.0.2

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_primary_s3#160]
### Reason
- Set max version to 10 for Semver

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Test: Install from the provided tarball and enable in ownCloud stable10

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/files_primary_s3/pull/159
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/files_primary_s3/pull/159
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist`: https://cloud.owncloud.com/index.php/f/4543213
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/files_primary_s3/pull/162

**Comment by PVince81** [comment]
@davitol please test RC1: https://cloud.owncloud.com/index.php/f/4543213

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready

**Comment by PVince81** [comment]
@DeepDiver1975 please push to marketplace: https://cloud.owncloud.com/index.php/s/t2VcCahExmjccmV

changelog: https://github.com/owncloud/files_primary_s3/blob/release-1.0.1/CHANGELOG.md#101

**Comment by PVince81** [comment]
weird, marketplace says the app is not signed

**Comment by PVince81** [comment]
seems no signature.json in tarball.
also no signing key... hmmm
