### ISSUE TITLE
Files Primary S3 1.0.3

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_primary_s3#175]
### Reason
- [x] Tarball broken for some envs due to non-gnu tar, see https://github.com/owncloud/files_primary_s3/pull/174

### QA
- [ ] Create **QA Milestone**
- [ ] Move items from `development` to `qa` 
- [ ] Create release branch with the format "release-$version"
- [x] Test new tarball @davitol https://github.com/owncloud/files_primary_s3/issues/175#issuecomment-452642952

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` and upload as Github release => https://github.com/owncloud/files_primary_s3/releases/tag/v1.0.3RC1
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist` and upload as Github release
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/files_primary_s3/pull/177

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/files_primary_s3/issues/60 (Primary S3 1.0.0 release checklist), https://github.com/owncloud/files_primary_s3/issues/61 (1.0.0 Testplan), https://github.com/owncloud/files_primary_s3/issues/160 ([For Semver] Files Primary S3 1.0.2), https://github.com/owncloud/files_primary_s3/pull/159 (Prepare for 1.0.1 release), and https://github.com/owncloud/files_primary_s3/pull/162 (Release 1.0.2).

**Comment by PVince81** [comment]
@davitol please smoke test https://github.com/owncloud/files_primary_s3/releases/tag/v1.0.3RC1 and check the vendor folder in particular for the file that was missing in https://github.com/owncloud/files_primary_s3/issues/171

**Comment by davitol** [comment]
1) Install the app via tarball: ```occ market:install -l files_primary_s3-1.0.3RC1.tar.gz```
2) Enable the app: ```occ app:enable files_primary_s3```

**Test result:**

apps/files_primary_s3/vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ApiCallAttemptMonitoringMiddleware.php now appears with .php extension

**Comment by PVince81** [comment]
bug in integrity check: https://github.com/owncloud/core/issues/34075

**Comment by davitol** [comment]
@PVince81 Tarball for v1.0.3RC1 does not contain Changelog file

**Comment by PVince81** [comment]
@davitol should be there now https://github.com/owncloud/files_primary_s3/releases/tag/v1.0.3RC2

**Comment by davitol** [comment]
@PVince81 thanks, I have checked that changelog now is included.
 
Also I checked the app keeps working updating with the tarball:

```
occ market:upgrade -l files_primary_s3-1.0.3RC2.tar.gz
files_primary_s3: Installing new version from files_primary_s3-1.0.3RC2.tar.gz.
files_primary_s3: App updated.
```

Files uploaded are kept and we can upload new ones

```
aws s3 ls s3://owncloud --endpoint-url=http://s3server:8000
2019-01-09 09:48:07    4916123 urn:oid:11
2019-01-09 09:48:07      36227 urn:oid:13
2019-01-09 09:48:08     228761 urn:oid:15
2019-01-09 09:48:08     233724 urn:oid:16
2019-01-09 09:48:08     216071 urn:oid:17
2019-01-09 09:48:40      30585 urn:oid:18
2019-01-09 09:48:45      25085 urn:oid:21
2019-01-09 09:48:45        951 urn:oid:22
2019-01-09 10:10:59     164603 urn:oid:23
2019-01-09 10:11:05     134534 urn:oid:25
2019-01-09 10:11:05        591 urn:oid:26
````


Also checked agaiin that ApiCallAttemptMonitoringMiddleware.php file is not truncated

So IMHO the tarball is QA-ready
