### ISSUE TITLE
[Stricly 10.3] Files Primary S3 1.0.4

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_primary_s3#209]
### Reason

- Release needed for #212 
❗️ version needs a specific min-version for core - see #212 and https://github.com/owncloud/core/pull/35144

### QA

- [x] Create **QA Milestone** @patrickjahns 
- [x] Move items from `development` to `qa` @patrickjahns 
- [x] Create release branch with the format "release-$version" @patrickjahns 
- [x] Create "$version Testplan" - will be done with 10.3.0alpha/beta testing  https://github.com/owncloud/files_primary_s3/issues/245 @davitol

### Documentation

- [x] Changes in the docs needed? not needed

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Check/adapt info.xml stuff
- [x] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)  @patrickjahns 
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)  @patrickjahns 

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch  @patrickjahns 
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)  @patrickjahns 
- [x] Upload as Github release using changelog entries  @patrickjahns 
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch https://github.com/owncloud/files_primary_s3/issues/245 @davitol

#### Final

- [x] Create github tag for final 'v${version}' on release branch @micbar 
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build) @micbar 
- [x] Upload as Github release using changelog entries @micbar
- [x] Smoke test tarball (at least install + enable) @davitol 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details) @micbar 
- [x] Publish tarball for customers (see handbook for details) @micbar 
- [x] Send mail to release-coordination with link to this ticket and to the changelog @micbar 

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by patrickjahns** [comment]
1.0.4RC1 is available here https://github.com/owncloud/files_primary_s3/releases/tag/v1.0.4RC1

Will be included in 10.3.0alpha for testing - no independent tests for now

**Comment by PVince81** [comment]
RC2: https://github.com/owncloud/files_primary_s3/releases/tag/v1.0.4RC2

we just updated the SDK again to align with files_external_s3

@davitol FYI

**Comment by davitol** [comment]
> RC2: https://github.com/owncloud/files_primary_s3/releases/tag/v1.0.4RC2

@PVince81 @micbar Files Primary S3 Rc2 Tarball is QA-ready

**Comment by micbar** [comment]
@davitol Created Final Tarball
Please smoke-test :-)

**Comment by davitol** [comment]
> @davitol Created Final Tarball
> Please smoke-test :-)

Tarball is QA-ready. OK for the release.
