### ISSUE TITLE
sabre/http 5.0.4 causes CI to hang

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_primary_s3#274]
After bumping `sabre/http` to 5.0.4 in core, then these CI jobs are hanging:
https://drone.owncloud.com/owncloud/files_primary_s3/1305/20/18
```
  Scenario: restoring file to old version changes the content of the file                                   # /var/www/owncloud/testrunner/tests/acceptance/features/webUIFiles/versions.feature:25
    Given user "user0" has uploaded file with content "lorem content" to "/randomfile.txt"                  # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "user0" has logged in using the webUI                                                          # WebUILoginContext::theUserLogsInUsingTheWebUI()
    And the user has browsed to the files page                                                              # WebUIFilesContext::theUserBrowsesToTheFilesPage()
    And user "user0" has uploaded file with content "new lorem content" to "/randomfile.txt"                # FeatureContext::userHasUploadedAFileWithContentTo()
    When the user browses directly to display the "versions" details of file "randomfile.txt" in folder "/" # WebUIFilesContext::theUserBrowsesDirectlyToDetailsTabOfFileInFolder()
    And the user restores the file to last version using the webUI                                          # WebUIFilesContext::theUserRestoresTheFileToLastVersionUsingTheWebui()
```
The output hangs at that point.

https://drone.owncloud.com/owncloud/files_primary_s3/1305/60/16
```
  Scenario: Restore a file and check, if the content is now in the current file               # /var/www/owncloud/testrunner/tests/acceptance/features/apiVersions/fileVersions.feature:58
    Given user "user0" has uploaded file with content "123" to "/davtest.txt"                 # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "user0" has uploaded file with content "12345" to "/davtest.txt"                 # FeatureContext::userHasUploadedAFileWithContentTo()
    And the version folder of file "/davtest.txt" for user "user0" should contain "1" element # FilesVersionsContext::theVersionFolderOfFileShouldContainElements()
    When user "user0" restores version index "1" of file "/davtest.txt" using the WebDAV API  # FilesVersionsContext::userRestoresVersionIndexOfFile()
```
The output hangs at that point.

**Comment by phil-davis** [comment]
I suspect that `files_primary_s3` might use `sabre/http` underneath when accessing the backend S3 object storage. The tests that hang are ones where the user tries to restore a version, and on S#  storage it can handle various version stuff itself. So maybe the server is going into a loop "forever" trying to process that on the backend S3 storage.

Or maybe it is a completely different problem.

Needs investigation.

**Comment by phil-davis** [comment]
@micbar there is no huge rush for this. We can leave `sabre/http` pinned at 5.0.2 for a while. But we should move forward at some point.

I am suspicious that there will be some other edge case problem with the upstream 5.0.4 release, which we could report and fix if we investigate this here. (There might be other projects using this that could benefit from some edge case being found and fixed)

e.g. I fixed a problem in 5.0.3 by PR https://github.com/sabre-io/http/pull/133

You can whatever labels, priority, scheduling...

**Comment by ho4ho** [comment]
> there is no huge rush for this. We can leave sabre/http pinned at 5.0.2 for a while.

sabre/http 5.0.4 "Significantly improve file download speed" by https://github.com/sabre-io/http/pull/119 :cry:

**Comment by phil-davis** [comment]
@dpakach has reproduced this on his local machine with S3 object storage and `sabre/http` 5.0.4. The server does go into a CPU loop. When he adds some "hack" code to just break out of the `while` loop https://github.com/sabre-io/http/blob/master/lib/Sapi.php#L111 after 20 iterations, then our test passes. I guess that the correct body of the file has been streamed out OK, but somehow "at the end" the `while` loop "gets in a spin" and the exit condition of the `while` loop is never satisfied.

He will continue tomorrow morning to debug what is going on in https://github.com/sabre-io/http/blob/master/lib/Sapi.php

Switching back to `sabre/http` 5.0.2 makes the test pass.

**Comment by vfreex** [comment]
> @dpakach has reproduced this on his local machine with S3 object storage and `sabre/http` 5.0.4. The server does go into a CPU loop. When he adds some "hack" code to just break out of the `while` loop https://github.com/sabre-io/http/blob/master/lib/Sapi.php#L111 after 20 iterations, then our test passes. I guess that the correct body of the file has been streamed out OK, but somehow "at the end" the `while` loop "gets in a spin" and the exit condition of the `while` loop is never satisfied.
> 
> He will continue tomorrow morning to debug what is going on in https://github.com/sabre-io/http/blob/master/lib/Sapi.php
> 
> Switching back to `sabre/http` 5.0.2 makes the test pass.

PR https://github.com/sabre-io/http/pull/137 adds a check to the copy stream function and raise an exception if it returns `false`. But I think it may need further investigation on why the copy stream function fails.

**Comment by ho4ho** [comment]
> But I think it may need further investigation on why the copy stream function fails.

Maybe related/similar by `file_exists()` like in https://github.com/owncloud/core/issues/33485#issuecomment-558409255 ?

**Comment by ho4ho** [comment]
Fixed by https://github.com/sabre-io/http/pull/138

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/36490 implements `sabre/http` 5.0.5
let's see the result

**Comment by phil-davis** [comment]
Fixed by https://github.com/owncloud/core/pull/36490
Confirmed by running the tests with files_primary_s3 in https://github.com/owncloud/files_primary_s3/pull/279
Closing.
