### ISSUE TITLE
files_primary_s3 1.1.2

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/files_primary_s3#326]
Reason 

- [x] https://github.com/owncloud/enterprise/issues/3838#issuecomment-598872824

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "files primary s3 1.1.2" Test Plan https://github.com/owncloud/files_primary_s3/issues/339 @davitol 

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Translations
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
Due to changes in the release branch (https://github.com/owncloud/files_primary_s3/issues/328) v1.1.2RC1 won't be used for creating the first RC2. I'm creating a new v1.1.2RC2 tag now

**Comment by HanaGemela** [comment]
RC2 for testing https://github.com/owncloud/files_primary_s3/releases/tag/v1.1.2RC2 @davitol

**Comment by davitol** [comment]
> RC2 for testing https://github.com/owncloud/files_primary_s3/releases/tag/v1.1.2RC2 @davitol

Back to DEV: https://github.com/owncloud/enterprise/issues/3838#issuecomment-616994593

**Comment by phil-davis** [comment]
PR #340 has been merged. Translations should be included in the next tarball.
@HanaGemela IMO the next RC can be made.

**Comment by HanaGemela** [comment]
@davitol RC3 ready https://github.com/owncloud/files_primary_s3/releases/tag/v1.1.2RC3

**Comment by davitol** [comment]
https://github.com/owncloud/enterprise/issues/3840#issuecomment-619868921

**Comment by davitol** [comment]
> @davitol RC3 ready https://github.com/owncloud/files_primary_s3/releases/tag/v1.1.2RC3

@HanaGemela Tarball is QA-ready

**Comment by HanaGemela** [comment]
@pmaier1 are you OK with a release with a newly found issues?
