### ISSUE TITLE
Extension of Scality tests - Artesca

### ISSUE THREAD

**Issue by michl19** [owncloud/files_primary_s3#456]
Please extend the ongoing Scality test to Artesca, endpoint: ttps://artesca.isv.scality.com
Access keys via mail already at Phils place.
As always, keep in mind this is a virtual environment so performance and space are limited (10's GB capacity is fine).

General infor on Artesca can be found here: https://www.scality.com/products/artesca

**Comment by phil-davis** [comment]
The test pipelines for Artesca should run in nightly CI. I will check the results tomorrow.

**Comment by phil-davis** [comment]
Test pipelines passed last night: https://drone.owncloud.com/owncloud/files_primary_s3/2363/167/18

Good.
