### ISSUE TITLE
Artesca S3 test storage unavailable to the drone CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_primary_s3#516]
This is some test storage of a "new" implementation of scality S3 storage. The test server has been provided externally.

For example:
https://drone.owncloud.com/owncloud/files_primary_s3/2650/160/16
```
Server error response [url] https://artesca.isv.scality.com/owncloud-acceptance-tests-2650-160 [status code] 503 [reason phrase] Service Unavailable
```

It has been "gone" for the last week or so.

**Comment by phil-davis** [comment]
@micbar how do we follow this up?

**Comment by phil-davis** [comment]
The server-under-test still does not exist: https://drone.owncloud.com/owncloud/files_primary_s3/2658

**Comment by micbar** [comment]
@phil-davis I spoke with partner management. They will follow up on this.

**Comment by phil-davis** [comment]
Note: this is still failing - https://drone.owncloud.com/owncloud/files_primary_s3/2692/149/17

It is no big problem, because these test pipelines are only run in nightly CI, and we know why it fails. CI for PRs to files_primary_s3 passes, so it does not block any developer.

**Comment by phil-davis** [comment]
@micbar any news?
should we stop testing this in every nightly CI??

**Comment by micbar** [comment]
still needs follow up on the partner side

**Comment by phil-davis** [comment]
New drone secret values were added yesterday. Nightly CI successfully accessed to Artesca S3 storage and the tests passed.

https://drone.owncloud.com/owncloud/files_primary_s3/2723
