### ISSUE TITLE
How to migrate from EBS to s3

### ISSUE THREAD

**Issue by vcrego** [owncloud/files_primary_s3#519]
Need guidance, Looking to move my owncloud community edition from EBS drive to S3 for data storage. 
Got quick que:
- This files_primary_s3 supported/work on owncloud community edition? Or need enterprise edition?
- How to migrate existing data and users to s3 based owncloud (files_primary_s3). Is there migration guide?
  - I tried attaching s3 to existing instance it doesn't identify/show existing data on EBS.
Thanks.

**Comment by mmattel** [comment]
Hello @vcrego 👋 
* S3 Primary can be uased with the community edition
* See the implications section in https://doc.owncloud.com/server/next/admin_manual/configuration/files/external_storage/s3_compatible_object_storage_as_primary.html#implications
* You could try to use the dataexporter (without guarantee), see https://doc.owncloud.com/server/next/admin_manual/maintenance/export_import_instance_data.html
