### ISSUE TITLE
Artesca server access forbidden

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_primary_s3#539]
9 days ago: https://drone.owncloud.com/owncloud/files_primary_s3/2755/149/17
```
Error executing "HeadBucket" on "https://artesca.isv.scality.com/owncloud-acceptance-tests-2755-149"; 
AWS HTTP error: Server error response [url] https://artesca.isv.scality.com/owncloud-acceptance-tests-2755-149
[status code] 503 [reason phrase] Service Unavailable  (server): 503 Service Unavailable
```

The same happened 8 days ago. Then 7 days ago: https://drone.owncloud.com/owncloud/files_primary_s3/2757/149/17
```
Error executing "CreateBucket" on "https://artesca.isv.scality.com/owncloud-acceptance-tests-2757-149"; 
AWS HTTP error: Client error response [url] https://artesca.isv.scality.com/owncloud-acceptance-tests-2757-149 
[status code] 403 
[reason phrase] Forbidden InvalidAccessKeyId (client): The AWS access key Id you provided does not exist in our records. - 
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>InvalidAccessKeyId</Code>
<Message>The AWS access key Id you provided does not exist in our records.</Message>
<Resource></Resource>
<RequestId>9686e9493741858ef866</RequestId>
</Error>            
```

Every nightly drone run since then up to last night has the same problem.

I guess that the provider has rebuilt that Artesca S3 test server again, and we need a new set of access keys.

**Comment by phil-davis** [comment]
@micbar ^

**Comment by oC-Chriddel** [comment]
Informed Scality. Will give an update asap.

**Comment by phil-davis** [comment]
@oC-Chriddel any news?

**Comment by phil-davis** [comment]
I have updated the credentials. PR #542 is running to check if it works.

**Comment by phil-davis** [comment]
Note: `scality_secret_access_key_artesca_escaped` has to have any forward-slash characters escaped in the secret stored in https://drone.owncloud.com/owncloud/files_primary_s3/settings/secrets

If the actual secret access key is `Qwertyuiop+SomeThing/Other123Stuff` then the `+` does not need to be escaped, but the `/` does. So the value to store in the secret would be:
`Qwertyuiop+SomeThing\/Other123Stuff`

This might help the next person who receives an new set of credentials.

**Comment by phil-davis** [comment]
CI passes with the new credentials that I received - see PR #542 

Thanks @oC-Chriddel
