### ISSUE TITLE
Is possible to use Google Cloud Storage

### ISSUE THREAD

**Issue by kevendoliveira** [owncloud/files_primary_s3#579]
Hello everyone, a small question, has anyone tried to use Google Cloud Storage compatible with this amazing plugin??

**Comment by jnweiger** [comment]
Haven't tried that, but as an external storage, you can for sure mount a google drive:

![image](https://user-images.githubusercontent.com/1108546/178770959-94c86096-3035-42fc-bcfd-940420207fe6.png)

**Comment by DeepDiver1975** [comment]
@jnweiger Google Cloud Storage  !== Google Drive

**Comment by DeepDiver1975** [comment]
@kevendoliveira Google Cloud Storage is s3 compatible and so it shall work. Give it a try and let us know. THX
