### ISSUE TITLE
Missing content in README.md

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_primary_s3#62]
@patrickjahns @DeepDiver1975 
This repro is going to be released soon see issue #60 and there is no readme.md
Please add content even this is boring and/or a bit consuming of your time.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @DeepDiver1975.

**Comment by mmattel** [comment]
![image](https://user-images.githubusercontent.com/3321281/41291718-bec48e04-6e50-11e8-9b0c-589efe80c2fc.png)

**Comment by mmattel** [comment]
Any update (pls) ?
![image](https://user-images.githubusercontent.com/3321281/44398219-64f57580-a543-11e8-8631-ebacf449cb84.png)

**Comment by DeepDiver1975** [comment]
PR welcome ;-) as usual
