### ISSUE TITLE
Nightly PHP unit-tests were killed after test run

### ISSUE THREAD

**Issue by SagarGi** [owncloud/files_primary_s3#628]
### Description 
Unit tests for the following pipelines were killed. Needs investigation why php unit test is killed

```
make: *** [Makefile:98: test-php-unit-dbg] Killed
```

### Drone build
https://drone.owncloud.com/owncloud/files_primary_s3/3267/6/8
https://drone.owncloud.com/owncloud/files_primary_s3/3267/8/8
https://drone.owncloud.com/owncloud/files_primary_s3/3267/9/8

**Comment by phil-davis** [comment]
```
Generating code coverage report in Clover XML format ... done [01:30.449]

make: *** [Makefile:98: test-php-unit-dbg] Killed
```

I have seen this before, "randomly". There is nothing reported about "why" it happened. If someone has an idea for how to track this down, great!

**Comment by kiranparajuli589** [comment]
Those failing suites are passing on the this rerun of today's nightly: https://drone.owncloud.com/owncloud/files_primary_s3/3268

**Comment by kiranparajuli589** [comment]
I will try to see what causes this..found this so far: https://github.com/sebastianbergmann/phpunit/issues/485

**Comment by SwikritiT** [comment]
@kiranparajuli589 this hasn't occurred, maybe it can be closed?

**Comment by kiranparajuli589** [comment]
The issue is anyway related to drone infrastructures. We can recheck on this if this happens again. Closing in favor of https://github.com/owncloud/files_primary_s3/issues/628#issuecomment-1369363422
