### ISSUE TITLE
Nightly fail `Error executing "CreateBucket"`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/files_primary_s3#642]
### Description
Nightly is failing on : 

` Error executing "CreateBucket" on "https://artesca.isv.scality.com/owncloud  
  -acceptance-tests-3344-145"; AWS HTTP error: cURL error 6: Could not resolv  
  e host: artesca.isv.scality.com (see https://curl.haxx.se/libcurl/c/libcurl  
  -errors.html) for https://artesca.isv.scality.com/owncloud-acceptance-tests  
  -3344-145     
`

Seems like a hard dailure and need some investigation on this.#641 

Build link : https://drone.owncloud.com/owncloud/files_primary_s3/3345/145/18

**Comment by saw-jan** [comment]
Could be the upstream issue

**Comment by phil-davis** [comment]
`cURL error 6: Could not resolve host: artesca.isv.scality.com`

The system that is provided externally for testing was not found. I suggest that we leave this issue here and see if it works better tonight. If there is the same problem again overnight, then we can contact someone "upstream" to find out what happened.

**Comment by phil-davis** [comment]
Note: a recent failure of these pipelines was issue #564 - if we need to contact upstream people, we can look there to see who we pinged.

**Comment by SagarGi** [comment]
https://drone.owncloud.com/owncloud/files_primary_s3/3346 failed today as well.

**Comment by phil-davis** [comment]
I don't think that anyone will respond between Christmas and New Year. We can ping people about this next Tuesday 2023-01-03. It is not urgent to fix, it does not stop any current development.

**Comment by SwikritiT** [comment]
https://drone.owncloud.com/owncloud/files_primary_s3/3352 failed today as well

**Comment by phil-davis** [comment]
`cURL error 6: Could not resolve host: artesca.isv.scality.com`

@oC-Chriddel the S3 server `artesca.isv.scality.com` that we use for these tests seems to have gone away since Christmas-New-Year sometime. Can you check with those responsible please, and see what happened?

**Comment by saw-jan** [comment]
From today: https://drone.owncloud.com/owncloud/files_primary_s3/3353/145

**Comment by SwikritiT** [comment]
Nightly passed today https://drone.owncloud.com/owncloud/files_primary_s3/3354

**Comment by saw-jan** [comment]
I will close it here!
