### ISSUE TITLE
Manual Test for Files Primary S3 

### ISSUE THREAD

**Issue by davitol** [owncloud/files_primary_s3#65]
| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| *Previous requirements: Have a primary storage configured for every file in the system (S3\| openstack swift)* |                                          |                |                 |
| Create 3 users, upload several files with user1, share some with user2, using user2 share some with user3. Using user3 download one of the files. | No problems. User3 can download the file. | ✅ |                 |
| Rename a file, in root and in a subsubfolder. | Files are renamed without problems.      | ✅  |                 |
| Using cadaver, copy a file from root to a subsubfolder. | Files are copied without problems.       | :construction: |                 |
| Connect desktop client. Sync a small file of about 1MiB. | File is uploaded and downloaded correctly. | ✅  |                 |
| Connect desktop client. Sync a file up to 256MiB, download it. | File is uploaded and downloaded correctly. | ✅  |                 |
| Federate share a folder and a file with another server which doesn't use objectstore. | Receiver can interact with the folder and file shared. | ✅            |                 |
| Federate share a folder and a file from another server which doesn't use objectstore with the server using objectstore. | User in objectstore server can interact with the folder shared. | ✅              |                 |
| Favorite several files and folders. Unfavorite them. Refresh page. | Files are favorited and unfavorited without problems. Check that state remains after refreshing. | ✅  |                 |
| Public share a folder and a file.        | Folder and file can be used normally by anonymous users. | ✅  |                 |
| Add comments to a shared file with several users. | No errors found.                         | ✅  |                 |
| Add comments to a shared folder with several users. | No errors found.                         | ✅  |                 |
| Add tags to a shared folder with several users. | No errors found.                         | ✅  |                 |
| Search tags previously assigned. | No errors found.                         | ✅  |                 |
| Check that activity is correctly recorded.  | No errors found.                         | ✅  |  |
| Set logging level to INFO. Check that user file actions are logged by admin audit.  | Actions are logged correctly.                       | :construction: | 
| Using the URL provided by user1: 1. enter the link.(without being logged in, use a different browser or have the cache cleaned) 2. Upload an existing file. | You can choose between cancel the upload and renaming the file. | ✅ |                 |

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @DeepDiver1975.

Possibly related issues are https://github.com/owncloud/files_primary_s3/pull/28 (Test against master again), https://github.com/owncloud/files_primary_s3/issues/49 (Add unit tests), and https://github.com/owncloud/files_primary_s3/issues/12 (Smashbox BasicSync fails with conflict files).

**Comment by davitol** [comment]
List of apps to check compatibility with objectstore:

Tested with a scality and a ceph server

  - [ ] admin_audit
  - [ ] comments
  - [ ] configreport
  - [ ] enterprise_key
  - [ ] files_antivirus
  - [ ] files_external (in general) - tested using sftp
  - [x] files_sharing
  - [x] files_trashbin
  - [ ] files_versions
  - [ ] firewall
  - [x] market
  - [ ] notifications
  - [ ] federatedfilesharing
  - [ ] oauth2
  - [ ] systemtags_management
  - [ ] theme-enterprise
  - [ ] user_ldap
  - [ ] workflow - ❌  files are not autotagged
 - [ ] encryption - ❌  Not working yet. QA and PM known.
 - [ ] password_policy
 - [ ] user_shibboleth
 - [ ] diagnostics
 - [ ] customgroups
 - [ ] guests 
 - [ ] test desktop client with big file (chunking)
 - [ ] test android with big file
 - [ ] test ios with big file
 - [ ] test clients which shared file/folder. upload/download
 - [ ] activity
 - [ ] gallery
 - [ ] impersonate
 - [ ] files_pdfviewer
 - [ ] files_texteditor
