### ISSUE TITLE
Initializing a new user leads to an empty version created of the skeleton file

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_primary_s3#66]
When first login in, a version for files in the skeleton directory are created.
Screenshots are missing for that version

# Steps to reproduce

1. As **admin** create user `bob`
2. Login as user **bob** 
3. Check versions tab of `welcome.txt` 

## Screenshot
![image](https://user-images.githubusercontent.com/6403243/40657946-e8deaaa6-6349-11e8-92fb-0d5e34bfeb01.png)

## Tested with
OwnCloud based on PR https://github.com/owncloud/core/pull/31050 and files_primary_s3

Behavior is not observed on ownCloud 10.0.8 docker containers:
![image](https://user-images.githubusercontent.com/6403243/40658056-3f568a5c-634a-11e8-8d97-dcc3b53ded92.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/owncloud/files_primary_s3/issues/53 (Restoring a previous version of a shared file fails).

**Comment by DeepDiver1975** [comment]
since s3 versioning is used the very first version on s3 is an empty file -> works as designed.

missing thumbnail is not nice ... but a different story
