### ISSUE TITLE
[nightly] Could not create s3 bucket (Will not follow more than 5 redirects)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/files_primary_s3#662]
Build: https://drone.owncloud.com/owncloud/files_primary_s3/3467/146/18

```
+ php occ s3:create-bucket owncloud-acceptance-tests-$DRONE_BUILD_NUMBER-$DRONE_STAGE_NUMBER --accept-warning

Creating bucket <owncloud-acceptance-tests-3467-146> ...

In WrappedHttpHandler.php line 195:                                                                      

  Error executing "CreateBucket" on "https://artesca.isv.scality.com/owncloud  
  -acceptance-tests-3467-146"; AWS HTTP error: Will not follow more than 5 re  
  directs Unable to parse error information from response - Error parsing XML  
  : String could not be parsed as XML                                          

In RedirectMiddleware.php line 155:

  Will not follow more than 5 redirects  

s3:create-bucket [--update-configuration] [--accept-warning] [--] <bucket>
```

**Comment by saw-jan** [comment]
^
CC @phil-davis

**Comment by phil-davis** [comment]
I guess that there is something changed with the connection to the "Artesca" S# storage provided by a 3rd party.
Let's see what happens in the coming days - maybe there is some DNS and network issue with it.
If it is not resolved by next Monday then we can ping them about igt.

**Comment by saw-jan** [comment]
Still an issue: https://drone.owncloud.com/owncloud/files_primary_s3/3473/145/18

**Comment by phil-davis** [comment]
@oC-Chriddel do you have any idea if something changed with reaching the Artesca S3 storage that is provided for testing?

**Comment by SwikritiT** [comment]
Still failing https://drone.owncloud.com/owncloud/files_primary_s3/3479/145/18

**Comment by SwikritiT** [comment]
failed today as well https://drone.owncloud.com/owncloud/files_primary_s3/3482/145/18

**Comment by phil-davis** [comment]
@micbar who should I contact about this?

There is a problem reaching the "Artesca" S3 server that is provided for use in tests.

**Comment by saw-jan** [comment]
Now failed due to the expiry of the SSL cert.
SSL certificate expired: https://github.com/owncloud/files_primary_s3/issues/602

**Comment by saw-jan** [comment]
Passing nightlies. Will close here
