### ISSUE TITLE
Thumbnails are not updated when editing a file

### ISSUE THREAD

**Issue by davitol** [owncloud/files_primary_s3#68]
## Steps to reproduce

1. Create a file.txt
2. Edit the file

**Expected behavior**

 The preview/Thumbnail should be updated

**Current behavior**

The preview/thumbnail is nor updated

## Screenshot
![thumbsca](https://user-images.githubusercontent.com/10596560/40668626-522da0c8-6365-11e8-9fbc-93a0d355abde.gif)

## Tested with
OwnCloud based on PR https://github.com/owncloud/core/pull/31050 and files_primary_s3 with scality

Behavior is not observed on ownCloud 10.0.8 docker containers:

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/files_primary_s3/issues/67 (Thumbnail preview of last version of a file does not work with scality), https://github.com/owncloud/files_primary_s3/issues/6 (Update aws sdk), and https://github.com/owncloud/files_primary_s3/issues/12 (Smashbox BasicSync fails with conflict files).

**Comment by davitol** [comment]
It seems to happen in regular storage too. See ticket https://github.com/owncloud/core/issues/31849

Closing this ticket and keep tracking in the issue pasted above.
