### ISSUE TITLE
Nightly failure in `phpunit-...` pipelines at install-core 

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/files_primary_s3#687]
Nightly builds failing at install-core in pipelines:

1. phpunit-scality-cov-php7.4-10.13.4-sqlite
2. phpunit-scality-mbuck-cov-php7.4-10.13.4-sqlite
3. phpunit-ceph-cov-php7.4-10.13.4-sqlite

```
$ wget -qO- https://download.owncloud.com/server/stable/owncloud-10.13.4-qa.tar.bz2 | tar -xj -C /tmp/owncloud/ --strip 1

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Builds: 
https://drone.owncloud.com/owncloud/files_primary_s3/4251
https://drone.owncloud.com/owncloud/files_primary_s3/4250
https://drone.owncloud.com/owncloud/files_primary_s3/4249
https://drone.owncloud.com/owncloud/files_primary_s3/4248
https://drone.owncloud.com/owncloud/files_primary_s3/4247
https://drone.owncloud.com/owncloud/files_primary_s3/4246
https://drone.owncloud.com/owncloud/files_primary_s3/4245
https://drone.owncloud.com/owncloud/files_primary_s3/4244
https://drone.owncloud.com/owncloud/files_primary_s3/4243

**Comment by saw-jan** [comment]
There's no `owncloud-10.13.4-qa.tar.bz2` in https://download.owncloud.com/server/stable

Also, I don't know why are we still running tests on `10.13.4`.
https://github.com/owncloud/files_primary_s3/blob/554f3616e1c8d717ab92ccf5d00bff0c6d23d25a/.drone.star#L79C18-L79C28

Maybe we should run tests with daily master and the latest released version?
CC @phil-davis

**Comment by jnweiger** [comment]
> There's no `owncloud-10.13.4-qa.tar.bz2` in https://download.owncloud.com/server/stable
> 
> Also, I don't know why are we still running tests on `10.13.4`.
> 
> https://github.com/owncloud/files_primary_s3/blob/554f3616e1c8d717ab92ccf5d00bff0c6d23d25a/.drone.star#L79
> 
> Maybe we should run tests with daily master and the latest released version? CC @phil-davis

@saw-jan I am surprised to see that https://download.owncloud.com/server/testing has only one release (currently 10.15.0) -- I always thought it is the same as /stable, where we accumulate many versions...

But yeah, there should be no need to run any tests against deprecated 10.13.4
