### ISSUE TITLE
Implement IVersionedStorage

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_primary_s3#7]
1. add IVersionedStorage to IObjectStoreStorage in https://github.com/owncloud/core/blob/master/lib/private/Files/ObjectStore/ObjectStoreStorage.php#L32
2. add IVersionesStorage to IObjectStore https://github.com/owncloud/core/blob/master/lib/public/Files/ObjectStore/IObjectStore.php#L30
3. implement s3 versioning in https://github.com/owncloud/files_primary_s3/blob/master/lib/s3storage.php

**Comment by tomneedham** [comment]
IVersionesStorage ??

**Comment by DeepDiver1975** [comment]
done ->close
