### ISSUE TITLE
'Storage wrapper 'oc_readonly' messages randomly appears in log file using Scality

### ISSUE THREAD

**Issue by davitol** [owncloud/files_primary_s3#70]
# Steps to reproduce

NOT YET KNOWN 

## ownCloud.log

```
{"reqId":"0UeELNP2ktByNobRyDsZ","level":2,"time":"2018-05-29T16:11:01+00:00","remoteAddr":"","user":"--","app":"filesystem","method":"--","url":"--","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
```

## Tested with
OwnCloud based on PR https://github.com/owncloud/core/pull/31050 and files_primary_s3 using scality.

Behavior is not observed on ownCloud 10.0.8 docker containers:

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @patrickjahns, and @ownclouders.
